# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }} (${{ matrix.arguments && 'all-traits' || 'no-traits' }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-26
            swift: "6.3"
            xcode: Xcode_26.4.1
          - os: macos-26
            swift: "6.3"
            xcode: Xcode_26.4.1
            arguments: "--traits X509,P256K,HTTP"
            coverage-report: true
          - os: macos-26
            swift: "6.2"
            xcode: Xcode_26.0.1
          - os: macos-26
            swift: "6.2"
            xcode: Xcode_26.0.1
            arguments: "--traits X509,P256K,HTTP"
          - os: macos-15
            swift: "6.1"
            xcode: Xcode_16.3
          - os: macos-15
            swift: "6.1"
            xcode: Xcode_16.3
            arguments: "--traits X509,P256K,HTTP"
          - os: ubuntu-latest
            swift: "6.3"
          - os: ubuntu-latest
            swift: "6.3"
            arguments: "--traits X509,P256K,HTTP"
          - os: ubuntu-latest
            swift: "6.2"
          - os: ubuntu-latest
            swift: "6.2"
            arguments: "--traits X509,P256K,HTTP"
          - os: ubuntu-latest
            swift: "6.1"
          - os: ubuntu-latest
            swift: "6.1"
            arguments: "--traits X509,P256K,HTTP"

    steps:
    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: ${{ matrix.swift }}
    - name: Select Xcode
      if: runner.os == 'macOS'
      run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app/Contents/Developer
    - uses: actions/checkout@v6
    - name: Get swift version
      run: swift --version
    - name: Build
      run: swift build -v ${{ matrix.arguments }}
    - name: Run tests
      run: swift test -v ${{ matrix.coverage-report && '--enable-code-coverage' || '' }} ${{ matrix.arguments }}
    - name: Submit code coverage
      if: matrix.coverage-report
      uses: vapor/swift-codecov-action@v0.3
      with:
        codecov_token: ${{ secrets.CODECOV_TOKEN }}